### PR TITLE
TPM emulation helper, make clean target and QEMU parametrization

### PR DESCRIPTION
**Pull request by orangecms**
With the `make clean` target, rebuilding is a bit easier:

```sh
make clean && make build//chainload/chainload && and make all
```

### CODE REVIEW

**Comment by osresearch** [comment]
Regarding https://github.com/osresearch/uefiblockdev/pull/7/commits/170f5624c2ad4fde2f375426d629b2a50dfdf3d8 -- oops.  Sorry!

Parameterizing qemu and having a better clean is a good idea.

Starting `swtpm` and generating state is a bit of a mess right now.  I have a makefile target (not checked in) that invokes it prior to starting qemu, as well as some helpers to extract the EK from the tpm state, but they are not ready for prime time.

**Comment by osresearch** [comment]
I've made some changes to the `Makefile` and `initrd/files.txt`; can you rebase?

**Comment by orangecms** [comment]
Done. Now I'm getting this here though:

```
make -C chainload
make[1]: Entering directory '/home/dama/firmware/uefiblockdev/chainload'
cc -O3 -W -Wall -g -m64 -MMD -MF ../build/chainload/.efi-entry.o.d  -D__efi__ -DGNU_EFI_USE_MS_ABI -fshort
tdlib -Wl,-eentry \
        -c \
        -o ../build/chainload/efi-entry.o \
        efi-entry.c \

efi-entry.c:63:1: fatal error: opening dependency file ../build/chainload/.efi-entry.o.d: No such file or
   63 | }
      | ^
```

which I can work around by reverting 2db1ea7d85d804c080fe744225c5d5615e755404 - did I miss something?

**Comment by osresearch** [comment]
There was a dep missing for creating `$O`. Should be fixed by https://github.com/osresearch/uefiblockdev/commit/e402e86c261ab5818e5364787b29744faad3e9e1

**Comment by orangecms** [comment]
> There was a dep missing for creating `$O`. Should be fixed by [e402e86](https://github.com/osresearch/uefiblockdev/commit/e402e86c261ab5818e5364787b29744faad3e9e1)

Indeed, that fixed it, thank you!

**Comment by osresearch** [comment]
I just made some large changes to `tpm.sh` to manage the swtpm state.  Please let me know if this breaks anything in your setup.  https://github.com/osresearch/uefiblockdev/commit/05d98a62871f01ab6c3e6e4d605b84e7c2083a1e

**Pull request merged**
